apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: {{ .Values.api.image }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ int .Values.api.port }}
          env:
            # Jwt Secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt-secret
            # Email Config
            - name: EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: email-address
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: email-username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: email-password
            - name: EMAIL_TEMPLATES_FOLDER
              value: "/app/templates"
            # Ysql Config
            - name: YSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ysql-username
            - name: YSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ysql-password
            - name: YSQL_HOST
              value: {{ .Values.api.ysql.host}} 
            - name: YSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ysql-db-name
            # Redis Config
            - name: REDIS_HOST_WRITE
              value: {{ .Values.api.redis.host.write }} 
            - name: REDIS_HOST_READ
              value: {{ .Values.api.redis.host.read }} 
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ int .Values.api.port }}
      targetPort: {{ int .Values.api.port }}
