deploy:
  - okteto ns use lbk2knewlifegithub && okteto kubeconfig
  - envsubst < config-template.yaml > config.yaml
  - kubectl apply -f config.yaml
  - rm config.yaml

  # Build api product-feedbacks PRODUCTION
  - okteto build -t okteto.dev/api-product-feedbacks:${OKTETO_GIT_COMMIT} api -f api/product-feedbacks.Dockerfile
  - helm upgrade -i api-product-feedbacks charts/api -n lbk2knewlifegithub -f values/prod/api-product-feedbacks.yaml --set tag=${OKTETO_GIT_COMMIT}

  # Apply ingress API
  - kubectl apply -f ingress/api-prod.yaml

  # Go to client namespace and build client image
  - okteto ns use client-lbk2knewlifegithub && okteto kubeconfig

  # Build client product feedbacks PRODUCTION
  - okteto build -t okteto.dev/client-product-feedbacks:${OKTETO_GIT_COMMIT} client -f client/product-feedbacks.Dockerfile
  - helm upgrade -i client-product-feedbacks charts/client -n client-lbk2knewlifegithub -f values/prod/client-product-feedbacks.yaml --set tag=${OKTETO_GIT_COMMIT}
