apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-prod
  namespace: lbk2knewlifegithub
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-auth
                port:
                  number: 8080
          - path: /api/v1/images/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-images
                port:
                  number: 8081
          - path: /api/v1/product-feedbacks/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-product-feedbacks
                port:
                  number: 8082
          - path: /api/v1/invoices/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-invoice-app
                port:
                  number: 8083
          - path: /api/v1/frontendmentor/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-frontendmentor
                port:
                  number: 8084
