// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: email_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultEmailSettings = `-- name: CreateDefaultEmailSettings :exec
INSERT INTO public.email_settings (user_id)
VALUES ($1)
`

func (q *Queries) CreateDefaultEmailSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createDefaultEmailSettings, userID)
	return err
}

const updateEmailSettings = `-- name: UpdateEmailSettings :exec
UPDATE public.email_settings
SET
    comment_on_solution = $1,
    reply_on_comment = $2,
    mention_in_comment = $3,
    earn_an_archivement = $4
WHERE user_id = $5
`

type UpdateEmailSettingsParams struct {
	CommentOnSolution bool      `json:"commentOnSolution"`
	ReplyOnComment    bool      `json:"replyOnComment"`
	MentionInComment  bool      `json:"mentionInComment"`
	EarnAnArchivement bool      `json:"earnAnArchivement"`
	UserID            uuid.UUID `json:"userID"`
}

func (q *Queries) UpdateEmailSettings(ctx context.Context, arg UpdateEmailSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailSettings,
		arg.CommentOnSolution,
		arg.ReplyOnComment,
		arg.MentionInComment,
		arg.EarnAnArchivement,
		arg.UserID,
	)
	return err
}
