// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	GetSolutionScreenshot(ctx context.Context, arg GetSolutionScreenshotParams) (sql.NullString, error)
	GetUserAvatar(ctx context.Context, userID uuid.UUID) (sql.NullString, error)
	UpdateSolutionScreenshot(ctx context.Context, arg UpdateSolutionScreenshotParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
}

var _ Querier = (*Queries)(nil)
