// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT u.avatar 
FROM public.users u 
WHERE u.user_id = $1
`

func (q *Queries) GetUserAvatar(ctx context.Context, userID uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatar, userID)
	var avatar sql.NullString
	err := row.Scan(&avatar)
	return avatar, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE public.users 
SET avatar = $1 
WHERE user_id = $2
`

type UpdateUserAvatarParams struct {
	Avatar sql.NullString `json:"avatar"`
	UserID uuid.UUID      `json:"userID"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.Avatar, arg.UserID)
	return err
}
