apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.apiStorage.name}}
spec:
  storageClassName: csi-okteto-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.apiStorage.storage.size}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.apiStorage.name}}
spec:
  replicas: {{ .Values.apiStorage.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.apiStorage.name}}
  template:
    metadata:
      labels:
        app: {{.Values.apiStorage.name}}
    spec:
      containers:
        - name: {{.Values.apiStorage.name}}
          image: {{ .Values.apiStorage.image }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ int .Values.apiStorage.port }}
          env:
            # Jwt Secret
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: jwt-secret
            # DB Config
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ysql-username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ysql-password
            - name: DB_HOST
              value: {{ .Values.api.ysql.host}} 
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ysql-db-name
            # Redis Config
            - name: REDIS_HOST_WRITE
              value: {{ .Values.apiStorage.redis.host.write }}
            - name: REDIS_HOST_READ
              value: {{ .Values.apiStorage.redis.host.read }}
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: redis-password
          volumeMounts:
            - name: {{.Values.apiStorage.name}}
              mountPath: {{.Values.apiStorage.storage.storageMountPath}}
      volumes:
        - name: {{.Values.apiStorage.name}}
          persistentVolumeClaim:
            claimName: {{.Values.apiStorage.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.apiStorage.name}}
spec:
  type: {{ .Values.apiStorage.serviceType }}
  selector:
    app: {{.Values.apiStorage.name}}
  ports:
    - port: {{ int .Values.apiStorage.port }}
      targetPort: {{ int .Values.apiStorage.port }}
