version: "3"
services:
  pg:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/lbk/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: >
      --requirepass example
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
