# WORKFLOW PRODUCTION
on:
  push:
    branches:
      - "master"
name: api-product-feedbacks

jobs:
  api-product-feedbacks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: deploy-api-product-feedbacks
          filename: .okteto/api-product-feedbacks.yaml
