# WORKFLOW PRODUCTION
on:
  pull_request:
    branches:
      - master
name: audiphile

jobs:
  audiphile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: deploy-prod
          filename: ./okteto/audiphile.yaml
