# File: .github/workflows/workflow.yml
# on:
#   pull_request:
#     branches:
#       - master
on:
  push:
    branches:
      - "master"
name: client-auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          name: client-lbk2knewlifegithub

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: client-auth
          namespace: client-lbk2knewlifegithub
          filename: okteto/client-auth.yaml
